### ISSUE TITLE
How to fix this issue?

### ISSUE THREAD

**Issue by hoover2015** [yukixz/cqbot#1]
C:\Python34\cqbot>python qqbot.py
Traceback (most recent call last):
  File "qqbot.py", line 11, in <module>
    from cqbot import CQBot, RE_CQ_SPECIAL, \
  File "C:\Python34\cqbot\cqbot.py", line 80

    ^
SyntaxError: can use starred expression only as assignment target

python-3.4.4

**Comment by yukixz** [comment]
Upgrade Python to 3.5+.

On Monday, 25 April 2016, hoover2015 <notifications@github.com> wrote:

> C:\Python34\cqbot>python qqbot.py
> Traceback (most recent call last):
> File "qqbot.py", line 11, in
> from cqbot import CQBot, RE_CQ_SPECIAL, \
> File "C:\Python34\cqbot\cqbot.py", line 80
>
> ^
>
> SyntaxError: can use starred expression only as assignment target
>
> python-3.4.4
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/yukixz/cqbot/issues/1>
>


-- 
*Dazzy Ding*
Email: h@dazzyd.org
